#!/usr/bin/env bash
mkdir -p dist
./node_modules/.bin/stylus --include src/loading < src/loading/index.styl > dist/loading.css
./node_modules/.bin/stylus --include src/loading --compress < src/loading/index.styl > dist/loading.min.css
