// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'slide-rtl',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1
    },
    offset: {
      'default': -200,
      type: 'number',
      unit: 'px',
      min: -2000,
      max: 2000
    }
  },
  code: function(config){
    return "slide(\"ld-slide-rtl\", config.dur, config.accelerate, config.offset, @(v) { transform: translate(v,0) })";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}