// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'blink',
  desc: '',
  edit: {
    dur: {
      'default': 1
    },
    showtime: {
      'default': 50,
      type: 'number',
      min: 0,
      max: 100
    },
    transitiontime: {
      'default': 1,
      type: 'number',
      min: 0,
      max: 100
    }
  },
  code: function(config){
    return "@keyframes ld-blink\n  0%\n    opacity: 1\n  {config.showtime * 1%}\n    opacity: 1\n  {(config.transitiontime + config.showtime) * 1%}\n    opacity: 0\n  {(100 - config.transitiontime) * 1%}\n    opacity: 0\n  100%\n    opacity: 1\n.ld-blink\n  animation: ld-blink config.dur linear infinite\n";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}