// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'blur',
  desc: '',
  edit: {
    blur: {
      'default': 10,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 100
    }
  },
  code: function(config){
    return "@keyframes ld-blur\n  0%\n    filter: blur(0)\n  50%\n    filter: blur(config.blur)\n  100%\n    filter: blur(0)\n.ld-blur\n  animation: ld-blur config.dur linear infinite\n";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}