// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'bounce',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.4,
      type: 'number',
      min: 0,
      max: 1
    },
    zoom_max: {
      'default': 1.1,
      type: 'number',
      min: 1,
      max: 2,
      step: 0.1
    },
    zoom_min: {
      'default': 0.5,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    offset_top: {
      'default': 27,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 3000
    },
    offset_bottom: {
      'default': 30,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 3000
    }
  },
  code: function(config){
    return "@keyframes ld-bounce\n  0%, 90%\n    animation-timing-function: linear\n  10%\n    timing-speed-down(config.accelerate)\n  50%\n    timing-speed-up(config.accelerate)\n  0%\n    transform: translate(0,config.offset_bottom) scaleY(config.zoom_min)\n  10%\n    transform: translate(0,5%) scaleY(config.zoom_max)\n  50%\n    transform: translate(0,-1 * config.offset_top) scaleY(config.zoom_max)\n  90%\n    transform: translate(0,5%) scaleY(config.zoom_max)\n  100%\n    transform: translate(0,config.offset_bottom) scaleY(config.zoom_min)\n.ld-bounce\n  animation: ld-bounce config.dur infinite";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}