// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'bounce-ltr',
  desc: '',
  edit: {
    dur: {
      'default': 3
    },
    offset_x: {
      'default': 50,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 1000
    },
    offset_y: {
      'default': 25,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 3000
    },
    offset_bottom: {
      'default': 25,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 3000
    },
    zoom_min: {
      'default': 0.7,
      type: 'number',
      min: 0,
      max: 1
    },
    zoom_max: {
      'default': 1.1,
      type: 'number',
      min: 1,
      max: 2
    }
  },
  code: function(config){
    return "@keyframes ld-bounce-ltr\n  for i in (0..3)\n    dx = i - 0.5\n    sgn = -1\n    {   0% + i * 25%}\n      transform: translate((dx + sgn * 1) * config.offset_x, config.offset_bottom) scaleY(config.zoom_min)\n    { 3.0% + i * 25%}\n      transform: translate((dx + sgn * 1) * config.offset_x, 0) scaleY(config.zoom_max)\n    { 4.2% + i * 25%}\n      transform: translate((dx + sgn * 0.84) * config.offset_x, -0.55 * config.offset_y) scaleY(config.zoom_max)\n    { 8.4% + i * 25%}\n      transform: translate((dx + sgn * 0.67) * config.offset_x, -0.88 * config.offset_y) scaleY(config.zoom_max)\n    {12.5% + i * 25%}\n      transform: translate((dx + sgn * 0.5) * config.offset_x, -1 * config.offset_y) scaleY(config.zoom_max)\n    {16.7% + i * 25%}\n      transform: translate((dx + sgn * 0.34) * config.offset_x, -0.88 * config.offset_y) scaleY(config.zoom_max)\n    {20.9% + i * 25%}\n      transform: translate((dx + sgn * 0.17) * config.offset_x, -0.55 * config.offset_y) scaleY(config.zoom_max)\n    {22.0% + i * 25%}\n      transform: translate((dx + sgn * 0) * config.offset_x, 0) scaleY(config.zoom_max)\n  100%\n    transform: translate(2.5 * config.offset_x, config.offset_bottom) scaleY(config.zoom_min)\n\n.ld-bounce-ltr\n  animation: ld-bounce-ltr config.dur infinite linear";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}