// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'bounce-ltr-alt',
  desc: '',
  edit: {
    dur: {
      'default': 2
    },
    offset_x: {
      'default': 60,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 1000
    },
    offset_y: {
      'default': 27,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 3000
    }
  },
  code: function(config){
    return "@keyframes ld-bounce-rtl-alt\n  for i in (0..3)\n    dx = -(i - 0.5)\n    sgn = 1\n    {   0% + i * 25%}\n      transform: translate((dx + sgn * 1) * config.offset_x, 0)\n    { 4.2% + i * 25%}\n      transform: translate((dx + sgn * 0.84) * config.offset_x, -0.55 * config.offset_y)\n    { 8.4% + i * 25%}\n      transform: translate((dx + sgn * 0.67) * config.offset_x, -0.88 * config.offset_y)\n    {12.5% + i * 25%}\n      transform: translate((dx + sgn * 0.5) * config.offset_x, -1 * config.offset_y)\n    {16.7% + i * 25%}\n      transform: translate((dx + sgn * 0.34) * config.offset_x, -0.88 * config.offset_y)\n    {20.9% + i * 25%}\n      transform: translate((dx + sgn * 0.17) * config.offset_x, -0.55 * config.offset_y)\n  100%\n    transform: translate(-2.5 * config.offset_x, 0)\n\n.ld-bounce-rtl-alt\n  animation: ld-bounce-rtl-alt config.dur infinite linear";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}