// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'clock',
  desc: '',
  edit: {
    dur: {
      'default': 12
    },
    accelerate: {
      'default': 0.7,
      type: 'number',
      min: 0,
      max: 1
    }
  },
  code: function(config){
    return "@keyframes ld-clock\n  0%\n    transform: rotate(0deg)\n  8.333%\n    transform: rotate(30deg)\n  16.667%\n    transform: rotate(60deg)\n  25%\n    transform: rotate(90deg)\n  33.333%\n    transform: rotate(120deg)\n  41.667%\n    transform: rotate(150deg)\n  50%\n    transform: rotate(180deg)\n  58.333%\n    transform: rotate(210deg)\n  66.667%\n    transform: rotate(240deg)\n  75%\n    transform: rotate(270deg)\n  83.333%\n    transform: rotate(300deg)\n  91.667%\n    transform: rotate(330deg)\n  100%\n    transform: rotate(360deg)\n.ld-clock\n  animation: ld-clock config.dur cubic-bezier(0,config.accelerate,1 - config.accelerate,1) infinite";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}