// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'float',
  desc: '',
  edit: {
    dur: {
      'default': 1
    },
    accelerate: {
      'default': 0.4,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    offset: {
      'default': 15,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 1000
    },
    zoom: {
      'default': 0.7,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    shadow_offset: {
      'default': 23,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 1000
    },
    shadow_blur: {
      'default': 5,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 100
    },
    shadow_expand: {
      'default': -15,
      type: 'number',
      unit: 'px',
      min: -1000,
      max: 1000
    }
  },
  code: function(config){
    return "@keyframes ld-float\n  0%\n    transform: translate(0,0) scale(config.zoom)\n    box-shadow: 0 0 0 rgba(0,0,0,.3)\n    timing-speed-down(config.accelerate)\n  50%\n    transform: translate(0,-1px * config.offset) scale(1)\n    timing-speed-up(config.accelerate)\n    box-shadow: 0 config.shadow_offset config.shadow_blur config.shadow_expand rgba(0,0,0,.2)\n  100%\n    transform: translate(0,0) scale(config.zoom)\n    box-shadow: 0 0 0 rgba(0,0,0,.3)\n.ld-float\n  animation: ld-float config.dur linear infinite\n";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}