// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'heartbeat',
  desc: '',
  edit: {
    dur: {
      'default': 0.8
    },
    accelerate: {
      'default': 0.5,
      type: 'number',
      min: 0,
      max: 1
    },
    offset: {
      'default': 10,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 30
    },
    max: {
      'default': 1.25,
      type: 'number',
      min: 1.05,
      max: 2
    },
    min: {
      'default': 0.9,
      type: 'number',
      min: 0,
      max: 1
    }
  },
  code: function(config){
    return "@keyframes ld-heartbeat\n  0%\n    transform: scale(1.05)\n  5%\n    transform: scale(config.max)\n  39%\n    transform: scale(config.min)\n  45%\n    transform: scale(1 + (config.max - 1) * 0.5)\n  60%\n    transform: scale(1.05)\n  100%\n    transform: scale(1.00)\n\n.ld-heartbeat\n  animation: ld-heartbeat config.dur infinite\n  timing-speed-down(config.accelerate)";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}