// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'hit',
  desc: '',
  edit: {
    dur: {
      'default': 2.0
    },
    accelerate: {
      'default': 0.5,
      type: 'number',
      min: 0,
      max: 1
    },
    zoom: {
      'default': 1,
      type: 'number',
      min: 0,
      max: 10
    },
    skew: {
      'default': 20,
      type: 'number',
      unit: 'deg',
      min: -90,
      max: 90
    },
    offset: {
      'default': 200,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 10000
    }
  },
  code: function(config){
    return "@keyframes ld-hit\n  0%\n    timing-speed-up(config.accelerate)\n    transform: scale(0) translate(0,0) skewX(0)\n  20%\n    transform: scale(config.zoom) translate(0,0) skewX(config.skew)\n  50%\n    //animation-timing-function: cubic-bezier(1,0,1,.5)\n    timing-speed-up(config.accelerate * 1.2)\n    transform: scale(config.zoom) translate(0,0) skewX(config.skew)\n  100%\n    transform: scale(config.zoom)  translate(0,config.offset) skewX(config.skew)\n.ld-hit\n  animation: ld-hit config.dur infinite\n";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}