// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'leaf',
  desc: '',
  edit: {
    dur: {
      'default': 4
    },
    count: {
      'default': 6,
      type: 'number',
      min: 0,
      max: 20,
      step: 2
    },
    accelerate: {
      'default': 0.3,
      type: 'number',
      min: 0,
      max: 1
    },
    offset_y: {
      'default': 200,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 1000
    },
    offset_x: {
      'default': 30,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 1000
    },
    degree: {
      'default': 30,
      type: 'number',
      unit: 'deg',
      min: 0,
      max: 90
    }
  },
  code: function(config){
    return "@keyframes ld-leaf\n  sgn = 1\n  for i in (0..config.count)\n    y1 = (i * config.offset_y / config.count) - config.offset_y * 0.5\n    y2 = ((i + 0.3) * config.offset_y / config.count) - config.offset_y * 0.5\n    {100 * i/config.count * 1%}\n      timing-speed-down(config.accelerate)\n      transform: translate(1px * sgn * config.offset_x,y1) rotate(0)\n    {100 * (i + 0.5)/config.count * 1%}\n      timing-speed-up(config.accelerate)\n      transform: translate(-.5px * sgn * config.offset_x,y2) rotate(config.degree * sgn * 1)\n    sgn = sgn * -1\n\n.ld-leaf\n  animation: ld-leaf config.dur linear infinite\n";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}