// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'slot',
  desc: '',
  edit: {
    dur: {
      'default': 6
    },
    count: {
      'default': 12,
      type: 'number',
      min: 4,
      max: 50
    },
    offset: {
      'default': 100,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 10000
    },
    variation: {
      'default': 1.1,
      type: 'number',
      min: 0,
      max: 10,
      step: 0.1
    }
  },
  code: function(config){
    return "@keyframes ld-slot\n  sum = 0\n  for i in (0..config.count)\n    x = (i - config.count * 0.5)\n    sum = sum + (1/(1 + config.variation * x * x))\n  cur = 0\n  for i in (0..config.count)\n    x = (i - config.count * 0.5)\n    offset = ((1/(1 + config.variation * x * x))) * 100 / sum\n    {cur * 1%}\n      transform: translate(0,-1px * config.offset)\n    {(cur + offset - 0.01) * 1%}\n      transform: translate(0,1px * config.offset)\n    cur = cur + offset\n  100%\n    transform: translate(0,-1px * config.offset)\n\n.ld-slot\n  animation: ld-slot config.dur linear infinite\n";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}