// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'squeeze',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.7,
      type: 'number',
      min: 0,
      max: 1
    },
    zoom_x: {
      'default': 0.5,
      type: 'number',
      min: 0,
      max: 3,
      step: 0.1
    },
    zoom_y: {
      'default': 0.5,
      type: 'number',
      min: 0,
      max: 3,
      step: 0.1
    }
  },
  code: function(config){
    return "@keyframes ld-squeeze\n  0%\n    transform: scale(1,config.zoom_y)\n  50%\n    transform: scale(config.zoom_x,1)\n  100%\n    transform: scale(1,config.zoom_y)\n.ld-squeeze\n  animation: ld-squeeze config.dur infinite\n  timing-speed-down(config.accelerate)";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}