// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'surprise',
  desc: '',
  edit: {
    dur: {
      'default': 1
    },
    zoom_min: {
      'default': 0.1,
      type: 'number',
      min: 0,
      max: 10,
      step: 0.1
    },
    zoom_max: {
      'default': 1.1,
      type: 'number',
      min: 0,
      max: 10,
      step: 0.1
    },
    skew: {
      'default': 35,
      type: 'number',
      unit: 'deg',
      min: -90,
      max: 90
    }
  },
  code: function(config){
    return "@keyframes ld-surprise\n  0%\n    transform: skewX(0deg) scale(1)\n  10%\n    transform: skewX(-1 * config.skew) scale(config.zoom_min)\n  20%\n    transform: skewX(-1 * config.skew) scale(config.zoom_min)\n  30%\n    transform: skewX(config.skew) scale(config.zoom_max)\n  40%\n    transform: skewX(-1 * config.skew) scale(config.zoom_max)\n  50%\n    transform: skewX(config.skew) scale(config.zoom_max)\n  60%\n    transform: skewX(-1 * config.skew) scale(config.zoom_max)\n  70%\n    transform: skewX(config.skew) scale(config.zoom_max)\n  80%\n    transform: skewX(-1 * config.skew) scale(config.zoom_max)\n  90%\n    transform: skewX(config.skew) scale(config.zoom_max)\n  100%\n    transform: skewX(-1 * config.skew) scale(config.zoom_max)\n\n.ld-surprise\n  animation: ld-surprise config.dur linear infinite\n";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}