// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'wrench',
  desc: '',
  edit: {
    dur: {
      'default': 1
    },
    rotate: {
      'default': 45,
      type: 'number',
      unit: 'deg',
      min: 0,
      max: 360
    }
  },
  code: function(config){
    return "@keyframes ld-wrench\n  20%, 36%, 70%, 86%\n    transform: rotate(0deg)\n  0%, 50%, 100%\n    transform: rotate(config.rotate * 1deg)\n.ld-wrench\n  animation: ld-wrench config.dur linear infinite\n";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}