// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'damage',
  desc: '',
  edit: {
    iterations: {
      'default': 10,
      type: 'number',
      min: 0,
      max: 50
    },
    offset: {
      'default': 1,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    ratio: {
      'default': 0.8,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    delay: {
      'default': 20,
      type: 'number',
      min: 0,
      max: 100,
      step: 0.1
    }
  },
  code: function(config){
    return "rubber(\"ld-damage\", config.dur, config.iterations, config.offset, config.ratio, config.delay, @(v) {\n  animation-timing-function: ease-out;\n  opacity: 1 - v;\n})";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}