// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'jingle',
  desc: '',
  edit: {
    iterations: {
      'default': 7,
      type: 'number',
      min: 0,
      max: 50
    },
    offset: {
      'default': 1,
      type: 'number',
      min: -10,
      max: 10,
      step: 0.1
    },
    ratio: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    delay: {
      'default': 10,
      type: 'number',
      min: 0,
      max: 100,
      step: 0.1
    }
  },
  code: function(config){
    return "rubber(\"ld-jingle\", config.dur, config.iterations, config.offset, config.ratio, config.delay, @(v) {\n  transform-origin: 50% 0%\n  animation-timing-function: ease-out\n  transform: rotate(v * 10deg);\n})";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}