// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'shake-v',
  desc: '',
  edit: {
    iterations: {
      'default': 5,
      type: 'number',
      min: 0,
      max: 50
    },
    offset: {
      'default': 10,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 20,
      step: 1
    },
    ratio: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    delay: {
      'default': 30,
      type: 'number',
      min: 0,
      max: 100,
      step: 0.1
    }
  },
  code: function(config){
    return "rubber(\"ld-shake-v\", config.dur, config.iterations, config.offset, config.ratio, config.delay, @(v) {\n  animation-timing-function: ease-out;\n  transform: translate(0,v);\n})";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}