// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'cycle',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.0,
      type: 'number',
      min: 0,
      max: 1
    },
    cycle: {
      'default': 360,
      type: 'number',
      unit: 'deg',
      min: 0,
      max: 3600,
      step: 360
    }
  },
  code: function(config){
    return "spin(\"ld-cycle\", config.dur, config.accelerate, config.cycle, @(v) {\n  transform: rotate(v)\n})";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}