// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'flip-h',
  desc: '',
  edit: {
    dur: {
      'default': 2
    },
    accelerate: {
      'default': 0.4,
      type: 'number',
      min: 0,
      max: 1
    },
    degree: {
      'default': 180,
      type: 'number',
      unit: 'deg',
      min: 0,
      max: 3600,
      step: 360
    }
  },
  code: function(config){
    return "x1 = 1\nx2 = 0\nx3 = 0\nx4 = 1\ny1 = 1\ny2 = 1\ny3 = 0\ny4 = 0\n\n.ld-flip\n  animation: ld-flip config.dur infinite\n@keyframes ld-flip\n  0%, 25%, 50%, 75%, 100%\n    timing-speed-down(config.accelerate)\n  0%\n    transform: rotateX(config.degree * x1) rotateY(config.degree * y1)\n  25%\n    transform: rotateX(config.degree * x2) rotateY(config.degree * y2)\n  50%\n    transform: rotateX(config.degree * x3) rotateY(config.degree * y3)\n  75%\n    transform: rotateX(config.degree * x4) rotateY(config.degree * y4)\n  100%\n    transform: rotateX(config.degree * x1) rotateY(config.degree * y1)";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}