// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'breath',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1
    },
    scale: {
      'default': 0.06,
      type: 'number',
      min: 0,
      max: 1
    }
  },
  code: function(config){
    return "patrol(\"ld-breath\", config.dur, config.accelerate, config.scale, @(v) {\n  transform: scale(1 + v * 2 - 0.03)\n})";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}