// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'dim',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1
    },
    opacity: {
      'default': 0.5,
      type: 'number',
      min: 0,
      max: 0.5
    }
  },
  code: function(config){
    return "patrol(\"ld-dim\", config.dur, config.accelerate, config.opacity, @(v) {\n  opacity: 0.5 + v\n})";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}