// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'metronome',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1
    },
    offset: {
      'default': 10,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 30
    },
    rotate: {
      'default': 30,
      type: 'number',
      unit: 'deg',
      min: 0,
      max: 30
    }
  },
  code: function(config){
    return "patrol(\"ld-metronome\", config.dur, config.accelerate, 1, @(v) {\n  transform: translate(v * config.offset,0) rotate(v * config.rotate)\n})";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}