// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'swing',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1
    },
    offset: {
      'default': 30,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 30
    },
    rotate: {
      'default': 30,
      type: 'number',
      unit: 'deg',
      min: 0,
      max: 30
    }
  },
  code: function(config){
    return "patrol(\"ld-swing\", config.dur, config.accelerate, config.rotate, @(v) { transform: rotate(v) })";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}