// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'wander',
  desc: '',
  edit: {
    accelerate: {
      'default': 0.6,
      type: 'number',
      min: 0,
      max: 1
    },
    offset: {
      'default': 10,
      type: 'number',
      unit: 'px',
      min: 0,
      max: 30
    }
  },
  code: function(config){
    return "patrol(\"ld-wander\", config.dur, config.accelerate, config.offset, @(v) {\n  transform: translate(v * 1px,0)\n})";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}