// Generated by LiveScript 1.3.1
var ret;
ret = {
  name: 'beat',
  desc: '',
  edit: {
    iterations: {
      'default': 1,
      type: 'number',
      min: 0,
      max: 10
    },
    accelerate: {
      'default': 0.4,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    decay: {
      'default': 0.5,
      type: 'number',
      min: 0,
      max: 1,
      step: 0.1
    },
    power: {
      'default': 1.1,
      type: 'number',
      min: 0,
      max: 10,
      step: 0.1
    },
    offset: {
      'default': 0.2,
      type: 'number',
      min: 0,
      max: 1
    }
  },
  code: function(config){
    return "bounce(\"ld-beat\", config.dur, config.iterations, config.accelerate, config.decay, config.power, config.offset,@(v) { transform: scale(1 + config.offset - v) })";
  }
};
if (typeof module != 'undefined' && module !== null) {
  module.exports = ret;
}